cfengine/cf-bottom

README.md

I'm doing this just to make a PR I can use to test GitHub API.

Added a small line of text to README

---

tom.py

See python docs for how and what to log:
https://docs.python.org/3/howto/logging.html

Added logging package

---

tom/bot.py
tom/github.py

Signed-off-by: Ole <ole.orhagen@northern.tech>

Give Tom the ability to read review comments

---

tom/github.py

Signed-off-by: Ole Petter <ole.orhagen@cfengine.com>

FIX: Tom was struggling to find himself

---

tom/bot.py
tom/github.py
tom/jenkins.py

Just include "exotic" in the comment triggering his builds.

CFE-2881: Tom can now start builds on exotic platforms

---

config.json

Add only craigcomstock and aleksandrychev as Mission portal reviewers

Change Mission portal reviewers

---

tom/bot.py
tom/github.py

Don't ping people when reviewers are already assigned

---

tom/dependencies.py

This updates tables in this file (only *master* branch):
https://github.com/Lex-2008/buildscripts/blob/master/deps-packaging/README.md
Command to run:
```
<@cf-bottom> depstable: 3.10.x,3.12.x,master
```
Example PR generated by the above command: https://github.com/cfengine/buildscripts/pull/560

ENT-4288 Teach Tom to update dependency table

---

config.json

This will allow him to trigger jenkins builds.

Added oleorhagen to list of trusted users

---

config.json

No thank you. I will keep using my own email for all of my commits.

Remove nick@cmdln.org from the list of banned emails

---

config.json

Add Ole Petter's banned e-mail and remove Kristian from reviewers

---

config.json
tom/bot.py
tom/packages.py

Sample PR: https://github.com/cfengine/system-testing/pull/333
----
#

ENT-6018 Teach tom to add packages to package_mapping.json file

---

config.json
tom/dependencies.py

Also Add build-tagging feature to cf-bottom
----
#

Stop adding empty lines to spec files

---

config.json

So that he can start jenkins builds using the "@cf-bottom
jenkins" prompt.

Add Lars Erik Wik as a trusted GH user

---

tom/packages.py
tom/tag.py

Otherwise, he wasn't able to decyper tag and crashed.
----
#

Tom follow-ups after 3.12.6 and 3.17.0 releases

---

tom/dependencies.py

They moved from README.md file in deps-packaging subdir to README.md in the repo
root, and also titles include URLs now, too.

Adapted Tom to new deptables location and layout

---

tom/dependencies.py

`sed 's/md5/sha256/' * && git commit && git push`

ENT-6774 Teach Tom to use sha256 when computing checksums

---

config.json
tom.cf
tom/bot.py
tom/github.py
tom/jenkins.py
tom/slack.py

When not using features related to parsing reviews, commits, and comments,
these changes significantly reduce the number of API requests needed.
This eliminates the 3 API requests we did for every PR, when they are not
needed for the enabled bot functionality.
More info:
https://tracker.mender.io/browse/SEC-140

Reduced the number of (unnecessary) API requests

---

tom/bot.py
tom/jenkins.py

Often a build that doesn't run unit and acceptance tests is
enough.

Teach Tom to start builds with no tests

---

tests/test_bot.py
tom/jenkins.py

Change fast docs pipeline BRANCH param to match jenkins job

---

tests/test_bot.py
tom/jenkins.py

Lex added jenkins config for SYSTEM_TESTING_REV several places.
Now Tom understands to include these in its requests.
Ticket: ENT-8295

ENT-8295: Taught Tom how to build with system-testig PRs

---

config.json

Forgot to include system-testing in jenkins_repos and repos (maintainers to nag to review) config.json
Ticket: ENT-8295

ENT-8295: Properly teach Tom how to build with system-testing PRs

---

tests/test_bot.py
tests/test_github.py
tom/jenkins.py

and fixed one item of system-testing should be only in
non fast doc builds
Ticket: ENT-8295

ENT-8295: Refined system-testing mention test

---

tom/changelog.py
tom/dependencies.py
tom/main.py
tom/packages.py
tom/tag.py

some changes required for cf-bottom to run smoothly and help with release

Release fixes

---

config.json

- the test containers are shared, but the majority of PRs is focused on backend testing related things
FYI @lluiscampos

aligned mender backend service repo responsibilities

---

tom/reports.py

See:
https://northerntech.atlassian.net/browse/SEC-880

SEC-880: Changed timeframe for stale dependabot PRs from 21 to 30 days

---

tom/reports.py

See:
https://northerntech.atlassian.net/browse/SEC-881

SEC-881: Excluded mender-test-containers from dependabot report

---

config.json

Tested locally, seems to work fine.

Added config for NorthernTechHQ org

---

tom/bot.py
tom/git.py

These allowed me to use bot Tom to do dependency updates.

A couple fixes for interactive use

---

README.md

Added instructions on using venv to install requirements
